### ISSUE TITLE
PR#989 Regression: etcd_object_counts for pods in prometheus report only have 7-9 pods when perf-test running

### ISSUE THREAD

**Issue by sonyafenge** [CentaurusInfra/arktos#1023]
**What happened**:

- Run perf-test with PR #987, which is the previous commit of PR #989, check etcd_object_counts for pods and pods were increasing to ~15K, then reduced to 9 after delete all deployments.

> Logs can be found under workload-controller-mamanger project at sonyadev4: /home/sonyali/logs/perf-test/gce-500/arktos/pr987-0312-1x500

> Git information

```
sonyali@sonyadev4:~/go/src/k8s.io/arktos$ git log --oneline
e679af0 Use HTTPS as etcd-apiserver protocol when mTLS is enabled (#987)
3ade140 Use secure communication for client <--> proxy communication, cleanup unnecessary config files (#986)
1ffad5c Read Arktos version from file instead of environment variable (#985)
```

- Run perf-test with PR# 989, check etcd_object_counts for pods and pods always keep to 7-9. And run “kubectl get pods -AT --kubeconfig test/kubemark/resources/kubeconfig.kubemark-proxy”, only see 9 system static pods, Cannot see any perf-test created pods.
> Logs can be found under workload-controller-mamanger project at sonyadev4: /home/sonyali/logs/perf-test/gce-500/arktos/pr989-0312-1x500

> Git information

```
sonyali@sonyadev4:~/go/src/k8s.io/arktos$ git log --oneline
30529a3 fix kubelet permission issue in kube-up (#996)
b0500d6 fix issue 655 (#992)
d111628 Consistent etcd key path (#989)
e679af0 Use HTTPS as etcd-apiserver protocol when mTLS is enabled (#987)
3ade140 Use secure communication for client <--> proxy communication, cleanup unnecessary config files (#986)
1ffad5c Read Arktos version from file instead of environment variable (#985)
```
**What you expected to happen**:
etcd_object_counts for pods number increasing/reducing correctly when pods is creating/deleting
**How to reproduce it (as minimally and precisely as possible)**:
Start scale-out 1tp, 1rp cluster with 500 hollow-nodes.
**Anything else we need to know?**:

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Sindica** [comment]
This issue is resolved with https://github.com/CentaurusInfra/arktos/pull/1027
