### ISSUE TITLE
perf test env setup enhancement works

### ISSUE THREAD

**Issue by yb01** [CentaurusInfra/arktos#1036]
This issue intends to capture needed improvements in perf test tools, namely, kube-up, kubemark, clusterloader etc. for Arktos 430 or beyound.

1. reduce test env setup time: such as parepare VMs in parallel, start hollow-nodes in parallel, cleanup VMs in parallel
2. variable naming consistency
3. make clear cut for AWS cloud providers -- currently some logic are in start-kubemark.sh which can be moved to AWS related libs

**Comment by sonyafenge** [comment]
these two files need be deleted when run stop-kubemark.sh, this will caused start-kubemark failed if already existing.
/tmp/haproxy_cfg_generator
/tmp/saved_tenant_ips.txt

**Comment by sonyafenge** [comment]
Detailed design information for this enhancement attached:
[kubeup-kubemark.script.pptx](https://github.com/CentaurusInfra/arktos/files/6239138/kubeup-kubemark.script.pptx)

**Comment by sonyafenge** [comment]
Keep this issue opened, still working on related items.
