### ISSUE TITLE
KCM (deployment controller) on TP cluster failed to sync up deployment with its token

### ISSUE THREAD

**Issue by yb01** [CentaurusInfra/arktos#1039]
**What happened**:

KCM (deployment controller) on TP cluster failed to sync up deployment with its token.

```
I0321 00:18:52.347999       1 deployment_controller.go:563] Started syncing deployment "arktos/v8uy5l-testns/saturation-deployment-0" (2021-03-21 00:18:52.347985815 +0000 UTC m=+665.382452865)
I0321 00:18:52.348391       1 deployment_util.go:260] Updating replica set "saturation-deployment-0-c47675f5" revision to 1
I0321 00:18:52.352163       1 deployment_controller.go:565] Finished syncing deployment "arktos/v8uy5l-testns/saturation-deployment-0" (4.172689ms)
I0321 00:18:52.352185       1 deployment_controller.go:485] Error syncing deployment arktos/v8uy5l-testns/saturation-deployment-0: replicasets.apps is forbidden: User "system:kube-controller-manager" cannot create resource "replicasets" in API group "apps" in the 
namespace "v8uy5l-testns"
```

append_or_replace_prefixed_line "${known_tokens_csv}" "${KUBE_CONTROLLER_MANAGER_TOKEN}," "system:kube-controller-manager,uid:system:kube-controller-manager"

**What you expected to happen**:
the controller should be permitted to perform the replication sets and create pods on the deployment

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Sindica** [comment]
Needs to check with tenant RBAC model

**Comment by yb01** [comment]
fixed in PR 1040
