### ISSUE TITLE
Failed to change ttl annotation for hollow-node

### ISSUE THREAD

**Issue by sonyafenge** [CentaurusInfra/arktos#1054]
**What happened**:
run perf-test with 1tp*1rp and get the error in kube-controller-manager

![image](https://user-images.githubusercontent.com/45471193/112707936-2dbe7200-8e6c-11eb-8d8b-dafe9c42a8f3.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/45471193/112707920-154e5780-8e6c-11eb-8113-bdfeebbfafb4.png)

![image](https://user-images.githubusercontent.com/45471193/112707916-0f587680-8e6c-11eb-9840-402cc165b519.png)

![image](https://user-images.githubusercontent.com/45471193/112707913-08316880-8e6c-11eb-8325-91420ea69c40.png)

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Sindica** [comment]
Checked v0.8 release perf test log located at sonyadev4:/home/sonyali/logs/perf-test/gce-50k/arktos/arktos-060321-50k-qps20/logs_density, both admin cluster and kubemark cluster, no such log in KCM.
This issue appears to be resolved.
