### ISSUE TITLE
TP2: Unable to authenticate the request due to an error: invalid bearer token

### ISSUE THREAD

**Issue by sonyafenge** [CentaurusInfra/arktos#1055]
**What happened**:
run perf-test with 2tp*1rp and get the error in kube-apiserver.log
![image](https://user-images.githubusercontent.com/45471193/112707996-8726a100-8e6c-11eb-9392-e29141281436.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/45471193/112708026-ade4d780-8e6c-11eb-8b93-bd36b14747d9.png)

![image](https://user-images.githubusercontent.com/45471193/112708030-b76e3f80-8e6c-11eb-9d75-0beecdef57e7.png)

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Sindica** [comment]
Same as https://github.com/CentaurusInfra/arktos/issues/1056
