### ISSUE TITLE
rp server failed to collect pprof files

### ISSUE THREAD

**Issue by sonyafenge** [CentaurusInfra/arktos#1057]
**What happened**:
rp server failed to collect pprof files because there is no kube-scheduler running. will have error:
```
Collecting kube-scheduler pprof at 2021-03-26-22:59:05
curl http://127.0.0.1:10251/debug/pprof/profile -o kube-scheduler-profile-2021-03-26-22:59:05.pprof
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed to connect to 127.0.0.1 port 10251: Connection refused
```

**What you expected to happen**:
no error and continue to collect pprof data
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Sindica** [comment]
Resolving as code merged.
