### ISSUE TITLE
[service support] arktos network controller: verify creating kubernetes + kube-dns service, kube-dns deployment on new network object

### ISSUE THREAD

**Issue by h-w-chen** [CentaurusInfra/arktos#1139]
**What would you like to be added**:
refer to [PR arktos-network-controller](https://github.com/CentaurusInfra/arktos/pull/313) for more background info.

mostly testing - in cluster where KCM (tenant controller) is running, and arktos network is running (as process is fine for this testing),
1. create a network object in a tenant, w/ flat type;
2. verify kubernetes_{network} and kube-dns_{network} service created;
3. verify kube-dns_{network} deployment is created, and its pods are running

**Why is this needed**:

**Comment by q131172019** [comment]
Verification steps in scale-up env (start by ./hack/arktos-up.sh") on AWS:

1. Create a network object in a tenant, w/ flat type;

In the first terminal:
0.1) (prerequisite) Ensure the others can read and write the file /var/run/docker.sock
```
sudo chmod o+rw /var/run/docker.sock; ls -al /var/run/docker.sock
```
0.2) (prerequisite) create the default network template file at ~/TMP/default_network.tmpl, with following content
```
{
    "metadata": {
        "name": "default"
    },
    "spec": {
        "type": "flat"
    }
}
```
1) ``` export ARKTOS_NETWORK_TEMPLATE="/home/ubuntu/TMP/default_network.tmpl" ```

2) run ``` ./hack/arktos-up.sh ``` to have scale-up dev cluster started

In second terminal:
3) run the following commands to start arktos network controller
```
make all WHAT=cmd/arktos-network-controller
ls -al ./_output/local/bin/linux/amd64/arktos-network-controller
 sudo ./_output/local/bin/linux/amd64/arktos-network-controller --kubeconfig=/home/ubuntu/.kube/config --kube-apiserver-ip=172.31.3.192 --kube-apiserver-port 6443
```

4) run ```./cluster/kubectl.sh get tenant```, should see system tenant is there
``
NAME       STORAGEID   STATUS   AGE
system     0           Active   114m
``

5) run ```./cluster/kubectl.sh get network -T```, should see the 'default" network under "system" tenant
``
NAME      TYPE   VPC   PHASE   DNS
default   flat         Ready   10.0.0.81
``
6) run ```./cluster/kubectl.sh create tenant mytenant``` to create new "mytenant" tenant

7) run ```./cluster/kubectl.sh get network --tenant mytenant```, should see it has "default" network created under the "mytenant" tenant
```
NAME      TYPE   VPC   PHASE   DNS
default   flat         Ready   10.0.0.219
```

**Comment by q131172019** [comment]
2. verify kubernetes_{network} and kube-dns_{network} service created;
2.1) run ```./cluster/kubectl.sh get service --all-namespaces --tenant system``` to verify system tenant
``
NAMESPACE     NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
default       kubernetes           ClusterIP   10.0.0.1     <none>        443/TCP                  138m
default       kubernetes-default   ClusterIP   10.0.0.73    <none>        443/TCP                  131m
kube-system   kube-dns             ClusterIP   10.0.0.10    <none>        53/UDP,53/TCP            138m
kube-system   kube-dns-default     ClusterIP   10.0.0.81    <none>        53/UDP,53/TCP,9153/TCP   131m
``

2.2) run ```./cluster/kubectl.sh get service --all-namespaces --tenant mytenant``` to verify mytenant tenant
```
NAMESPACE     NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
default       kubernetes-default   ClusterIP   10.0.0.116   <none>        443/TCP                  48m
kube-system   kube-dns-default     ClusterIP   10.0.0.219   <none>        53/UDP,53/TCP,9153/TCP   48m
```

**Comment by q131172019** [comment]
3. verify kube-dns_{network} deployment is created, and its pods are running

3.1) run ```./cluster/kubectl.sh get deployments,pods --all-namespaces --tenant system``` to verify system tenant
```
NAMESPACE     NAME                                    HASHKEY               READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.extensions/coredns-default   2303946025303038394   1/1     1            1           133m
kube-system   deployment.extensions/kube-dns          6268624095960167247   1/1     1            1           140m

NAMESPACE     NAME                                   HASHKEY               READY   STATUS    RESTARTS   AGE
kube-system   pod/coredns-default-755c76cc67-fwx6p   8409295997702801073   1/1     Running   0          85m
kube-system   pod/kube-dns-554c5866fc-x4fl9          2653046258417869634   3/3     Running   0          139m
kube-system   pod/virtlet-57zz6                      7614984515446065133   3/3     Running   0          139m
```

3.2) run ```./cluster/kubectl.sh get deployments,pods --all-namespaces --tenant mytenant``` to verify mytenant tenant
```
NAMESPACE     NAME                                    HASHKEY               READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.extensions/coredns-default   8451537908233599030   1/1     1            1           51m

NAMESPACE     NAME                                   HASHKEY               READY   STATUS    RESTARTS   AGE
kube-system   pod/coredns-default-755c76cc67-h9qnk   7966040532148112635   1/1     Running   0          48m
```

**Comment by h-w-chen** [comment]
for 1x1 scale out cluster, we may add a firewall rule to run on RP (assuming TP ip is 172.88.3.192)
```
sudo iptables -t nat -A PREROUTING -p tcp -d 10.0.0.1 --dport 443 -j DNAT --to-destination 172.88.3.192:6443
```

**Comment by q131172019** [comment]
Verification steps in Multi-node scale-up env (start by ./hack/arktos-up.sh") on AWS:


(prerequisite)Follow up the procedure https://github.com/q131172019/arktos/blob/CarlXie_singleNodeArktosCluster/docs/setup-guide/multi-node-dev-cluster.md to test two nodes(172.31.3.192 and 172.31.5.191) with Flannel network successfully.

1. Create a network object in a tenant, w/ flat type;
In the first terminal:
1.1) (prerequisite) Ensure the others can read and write the file /var/run/docker.sock
```
sudo chmod o+rw /var/run/docker.sock; ls -al /var/run/docker.sock
```
1.2) (prerequisite) create the default network template file at ~/TMP/default_network.tmpl, with following content
```
{
    "metadata": {
        "name": "default"
    },
    "spec": {
        "type": "flat"
    }
}
```
1.3) ``` export ARKTOS_NETWORK_TEMPLATE="/home/ubuntu/TMP/default_network.tmpl" ```
1.4) With above in place, just follow the [How to Setup a Dev Cluster of multi-nodes](https://github.com/q131172019/arktos/blob/CarlXie_singleNodeArktosCluster/docs/setup-guide/multi-node-dev-cluster.md).
1.5) After the system has been started, on master server, run the test commands

**Comment by q131172019** [comment]
The network controller has been verified to support flannel network in single node scale-up cluster and multi-node scale-up cluster.

The network controller has been verified NOT to support flannel network in 1TP X 1RP scale-out cluster with the following 2 opened issues
Issue #1156 - https://github.com/CentaurusInfra/arktos/issues/1156 - [scale-out] Flannel network fails to deploy as daemonset in scale-out cluster #1156

Issue #1157 - https://github.com/CentaurusInfra/arktos/issues/1157 - [scale-out] Flannel network fails to deploy with deployment mode in scale-out cluster #1157

**Comment by h-w-chen** [comment]
we may use kubelet --resolv-config to provide the dns setting (less intrusive), instead of changing host's /etc/resolv.conf.

**Comment by q131172019** [comment]
When I work on issue #1144 to start multi-node scale-up cluster, I will try to use kubelet --resolv-config to provide the dns setting (less intrusive), instead of changing host's /etc/resolv.conf as a test. Thanks!

**Comment by q131172019** [comment]
>>> we may use kubelet --resolv-config to provide the dns setting (less intrusive), instead of changing host's /etc/resolv.conf.

For multi-node scale-up cluster:

On master node, make the following changes:

1) in the file hack/lib/common-var-init.sh, add the following setting in line 217
```
RESOLV_CONF=${RESOLV_CONF:-"/run/systemd/resolve/resolv.conf"}
```

2) in the file hack/lib/common.sh, add the following setting in line 758
```
"--resolv-conf=${RESOLV_CONF}"
```

On worker node, make the following change:
1) in the file hack/arktos-worker-up.sh, add the following setting in line 75

```
--resolv-conf=/run/systemd/resolve/resolv.conf \
```

**Comment by q131172019** [comment]
For DNS setting: it is very helpful to work out the issue #1140.

On master node:
1. hack/lib/common-var-init.sh
```
grep -i dns hack/lib/common-var-init.sh
# and we don't know the IP of the DNS pod to pass in as --cluster-dns.
# To set this up by hand, set this flag and change DNS_SERVER_IP.
# Note also that you need API_HOST (defined above) for correct DNS.
ENABLE_CLUSTER_DNS=${KUBE_ENABLE_CLUSTER_DNS:-true}
ENABLE_NODELOCAL_DNS=${KUBE_ENABLE_NODELOCAL_DNS:-false}
DNS_SERVER_IP=${KUBE_DNS_SERVER_IP:-10.0.0.10}
LOCAL_DNS_IP=${KUBE_LOCAL_DNS_IP:-169.254.20.10}
DNS_MEMORY_LIMIT=${KUBE_DNS_MEMORY_LIMIT:-170Mi}
DNS_DOMAIN=${KUBE_DNS_NAME:-"cluster.local"}
```
2. hack/lib/common.sh
```
    # Enable dns
        dns_args=("--cluster-dns=${LOCAL_DNS_IP}" "--cluster-domain=${DNS_DOMAIN}")
        dns_args=("--cluster-dns=${DNS_SERVER_IP}" "--cluster-domain=${DNS_DOMAIN}")
      dns_args=("--cluster-dns=8.8.8.8")
      ${dns_args[@]+"${dns_args[@]}"}
```

On worker node:

3. hack/arktos-worker-up.sh
```
CLUSTER_DNS=${CLUSTER_DNS:-"10.0.0.10"}
--cluster-dns=${CLUSTER_DNS} \
```
