### ISSUE TITLE
[service support] end-to-end verification of service in scale-up cluster

### ISSUE THREAD

**Issue by h-w-chen** [CentaurusInfra/arktos#1142]
**What would you like to be added**:
E2E testing, with CNI fo Flanne (or Kube-Router),
1. inside of a pod
2. curl by service name, like http://nginx.ns.svc.cluster.local:8080

**Why is this needed**:

**Comment by q131172019** [comment]
0. Set up single node scale-up cluster by the following steps after get AWS EC2 instance (t2.2xlarge) 
0.1) Follow up the procedure at https://github.com/q131172019/arktos/blob/CarlXie_singleNodeArktosCluster/docs/setup-guide/setup-dev-env.md to set up development environment

0.2) Create single node scale-up cluster by following up the steps below  
```
  sudo chmod o+rw /var/run/docker.sock; ls -alg /var/run/docker.sock
  sudo rm -rf /etc/cni/net.d/10-flannel.conflist; sudo ls -alg /etc/cni/net.d/
  sudo rm -rf /etc/cni/net.d/bridge.conf; sudo ls -alg /etc/cni/net.d/
  export CNIPLUGIN="flannel"
  ./hack/arktos-up.sh
```
1.

**Comment by q131172019** [comment]
I verified above steps were working on 2021-09-26.

**Comment by q131172019** [comment]
I verified above steps were working on 2021-11-19 through 2021-11-21 again in scale-up multi-node environment running on AWS EC2 running Ubuntu 18/04.

Master node: ip-172-31-22-85
worker nodes: ip-172-31-24-185 and ip-172-31-29-128
