### ISSUE TITLE
[service support] kubelet: serviceLister only retrieves data from KubeTPClients[0]

### ISSUE THREAD

**Issue by q131172019** [CentaurusInfra/arktos#1180]
**What happened**:
https://github.com/CentaurusInfra/arktos/blob/8e5c308a2a1da21e18a8949db7224d16fba01f08/pkg/kubelet/kubelet.go#L444
- serviceLW (ListWatch) only lists and watches the service changes from KubeTPClients[0] (one TP). In M TPs X N RPs env, this is a bug.

**What you expected to happen**:
serviceLW (ListWatch) can lists and watches the service changes from KubeTPClients[i] (i = 0,1 ... M-1) in M TPs X N RPs env

**Comment by q131172019** [comment]
PR 1181 was sent out last Wednesday and approved last Thursday.

**Comment by h-w-chen** [comment]
PR #1181 merged in. This bug is fixed.
