### ISSUE TITLE
[kube-up][scale-out] TP master server is not up when DISABLE_ADMISSION_PLUGINS is not empty

### ISSUE THREAD

**Issue by q131172019** [CentaurusInfra/arktos#1326]
**What happened**:
During starting procedure, the following error comes out.
```
DBG: MASTER_EXTRA_METADATA : 
ERROR: (gcloud.compute.instances.create) Unable to read file [/tmp/tmp.2v0tQQ1O62/network.tmpl]: [Errno 2] No such file or directory: '/tmp/tmp.2v0tQQ1O62/network.tmpl'
Failed to create master instance due to non-retryable error
```
**What you expected to happen**:
TP master server should be up when DISABLE_NETWORK_SERVICE_SUPPORT=true

**How to reproduce it (as minimally and precisely as possible)**:

./cluster/kube-up.sh

**Anything else we need to know?**:

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools: 1 x 1 kube-up
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by q131172019** [comment]
Further investigation:
In kube-api log, second error was found.
```
https://github.com/CentaurusInfra/arktos/issues/1322
```

**Comment by q131172019** [comment]
https://github.com/CentaurusInfra/arktos/pull/1327 is opened for code review.

**Comment by h-w-chen** [comment]
per discussion, a separate PR will be created for this defect.
