### ISSUE TITLE
[kube-up][scale-out] mizar subnet has only /24 netmask

### ISSUE THREAD

**Issue by h-w-chen** [CentaurusInfra/arktos#1340]
**What happened**:
subnets created by arktos mizar controller seems too limitive, with /24 netmask
```
$ kubectl get subnet
NAME                            IP          PREFIX   VNI        VPC                      STATUS        BOUNCERS   CREATETIME                   PROVISIONDELAY
net0                            20.0.0.0    8        1          vpc0                     Provisioned   1          2022-02-07T17:56:10.671720   122.700976
system-default-network-subnet   21.0.21.0   24       13483883   system-default-network   Provisioned   1                 
```

**What you expected to happen**:
should have a bigger netmask, like /16.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools: kube-up scale-out 1+1x1
- Network plugin and version (if this is a network-related bug): mizar
- Others:

**Comment by h-w-chen** [comment]
the template file defines subnet template as "21.0.21.0/24". This may need proper change.

**Comment by Sindica** [comment]
Please comment on https://github.com/CentaurusInfra/arktos/pull/1342

**Comment by Sindica** [comment]
PR 1342 merged.
