### ISSUE TITLE
[kube-up][scale-out]mizar failed to start if dev machine missing kubectl

### ISSUE THREAD

**Issue by sonyafenge** [CentaurusInfra/arktos#1369]
**What happened**:
name: ying-scaleout-rp-1-minion-nodeports
network: https://www.googleapis.com/compute/v1/projects/workload-controller-manager/global/networks/ying-scaleout
priority: 1000
selfLink: https://www.googleapis.com/compute/v1/projects/workload-controller-manager/global/firewalls/ying-scaleout-rp-1-minion-nodeports
sourceRanges:
- 0.0.0.0/0
targetTags:
- ying-scaleout-rp-1-minion
DBG: copy rp kubeconfigs for scheduler and controller manager to TP master: ying-scaleout-tp-1-master
Warning: Permanently added 'compute.6763971189625875225' (ECDSA) to the list of known hosts.
kubeconfig.rp-1                                                                                                                                                                           100%   10KB  10.3KB/s   00:00    
DBG: copy rp kubeconfigs to destinations on TP master: ying-scaleout-tp-1-master
DBG: restart scheduler on TP master: ying-scaleout-tp-1-master
DBG: restart controller manager on TP master: ying-scaleout-tp-1-master
Installing Mizar for scale-out architecture...
./cluster/../cluster/../cluster/gce/util.sh: line 3425: kubectl: command not found

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Sindica** [comment]
Fixed
