### ISSUE TITLE
[Local dev env] Allow user to switch among different CNI plugin solutions

### ISSUE THREAD

**Issue by Sindica** [CentaurusInfra/arktos#1399]
**What would you like to be added**:
If I start arktos-up using mizar, and then shut down the cluster, use default (bridge) to start cluster, I got coredns pod stuck in container creating state. Manually delete /etc/cni/net.d/10-mizarcni.conf and restart cluster will fix the issue.

We would like to allow dev to use same machine to test different CNI plugin, currently supported: bridge, flannel, and mizar.

**Why is this needed**:
Better dev experience.

**Comment by q131172019** [comment]
PR1400 fixed this issue.
