### ISSUE TITLE
Support built-in resources (such as service "kubernetes") for tenant spaces

### ISSUE THREAD

**Issue by XiaoningDing** [CentaurusInfra/arktos#183]
(To add more details)

**Comment by chenqianfzh** [comment]
Per discussion with Hongwei and Pengdu, this issue does not block the feature of multi-tenancy CRD, as multi-tenancy CRD can work end-to-end via configuration in user context. 

Yet, we agree this issue is a critical issue in multi-tenancy networking. So I assign it to Xiaoning.

**Comment by h-w-chen** [comment]
Mechanism of service kubernetes in arktos multi-tenancy is in part of [service design proposal](https://github.com/futurewei-cloud/arktos/pull/206). 
Plan to implement it in future milestone 6/30.

**Comment by h-w-chen** [comment]
core-dns pod is house-keeping the default kubernetes + kube-dns service for rach network; closed
