### ISSUE TITLE
perf-tests: APIResponsiveness is extremely higher with 06/29 build compared with all previous arktos versions

### ISSUE THREAD

**Issue by sonyafenge** [CentaurusInfra/arktos#456]
**What happened**:
Follow perf-tests process to start perf-tests and check perf-test result, APIResponsiveness data are extremely higher than previous version

**What you expected to happen**:
APIResponsiveness data are same or lower then previous version

**How to reproduce it (as minimally and precisely as possible)**:
run perf-tests following instruction: 
https://github.com/sonyafenge/arktos-tool/blob/master/perftools/Howtorunperf-tests.md 

check perf results and get the data as below:
![image](https://user-images.githubusercontent.com/45471193/86839210-feee3a80-c055-11ea-9247-58301bed28bc.png)
![image](https://user-images.githubusercontent.com/45471193/86839226-031a5800-c056-11ea-9806-d169483aaeb8.png)

**Anything else we need to know?**:
Test Environemnts: 
```
admin master: 1 | n1-highmem-32 (32 vCPUs, 208 GB memory)      | cos-73-11647-163-0
Admin nodes: 7 | n1-highmem-8 (8 vCPUs, 52 GB memory) |     cos-73-11647-163-0
kubemark master: 1 | n1-highmem-32 (32 vCPUs, 208 GB memory)      | cos-73-11647-163-0
```

```
Software Build: Arktos 06/29/2020
Nodes: 500
Cloud Provider: GCE
APISERVERS_EXTRA_NUM=0
```

**Environment**:
- Arktos version (use `kubectl version`):
```
arktos 06/29/2020 build
commit 8b7b6554fb46e08f0bad5968a563857d0ad4c55f
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Sindica** [comment]
List latency increase might be related to this change: https://github.com/futurewei-cloud/arktos/pull/207

**Comment by Sindica** [comment]
Are those latency average/tp50/75/90/95/99?

**Comment by sonyafenge** [comment]
these data are perc99.

**Comment by sonyafenge** [comment]
[APIResponsivenessPrometheus_simple_density_2020-07-03T23:37:30Z.xlsx](https://github.com/futurewei-cloud/arktos/files/4900916/APIResponsivenessPrometheus_simple_density_2020-07-03T23.37.30Z.xlsx)

**Comment by sonyafenge** [comment]
[prealkaid_APIResponsiveness_density_2020-01-17T00:19:23Z.xlsx](https://github.com/futurewei-cloud/arktos/files/4903878/prealkaid_APIResponsiveness_density_2020-01-17T00.19.23Z.xlsx)

**Comment by sonyafenge** [comment]
Root cause has been addressed in different issue: https://github.com/CentaurusInfra/arktos/issues/478
closing this issue for now.
