### ISSUE TITLE
cluster missing kube-controller-manager endpoints after disable workload-controller-manager

### ISSUE THREAD

**Issue by sonyafenge** [CentaurusInfra/arktos#462]
**What happened**:
impacted by workload throughput issue: https://github.com/futurewei-cloud/arktos/issues/96, disable workload-controller-manger to run perf-tests. after disable workload-controller-manager and found cluster missing kube-controller-manager endpoints

**What you expected to happen**:
after disable workload-controller-manager, kube-controller-manager endpoints still exist.
**How to reproduce it (as minimally and precisely as possible)**:
1. git clone arktos
2. make clean & make quick-release
3. run ./cluster/kube-up.sh to start cluster
5. check endpoints
```
$ kubectl get endpoints --all-namespaces
NAMESPACE     NAME                      ENDPOINTS                            AGE   SERVICEGROUPID
default       kubernetes                34.94.73.126:443                      28m   0
kube-system   default-http-backend      10.64.5.3:8080                       27m
kube-system   heapster                  10.64.4.2:8082                       27m
kube-system   kube-controller-manager   <none>                               28m   <none>
kube-system   kube-scheduler            <none>                               28m   <none>
kube-system   kubernetes-dashboard      10.64.7.2:8443                       27m
kube-system   metrics-server            10.64.6.2:443                        27m
kubemark      kube-dns                  10.64.8.2:53,10.64.8.2:53            21m
```
6. following the git diff below to disable workload-controller-manger
```
diff --git a/cluster/gce/gci/configure-helper-common.sh b/cluster/gce/gci/configure-helper-common.sh
index 59b2e08..67903cf 100644
--- a/cluster/gce/gci/configure-helper-common.sh
+++ b/cluster/gce/gci/configure-helper-common.sh
@@ -2038,6 +2038,7 @@ function start-kube-controller-manager {
   params+=" --use-service-account-credentials"
   params+=" --cloud-provider=gce"
   params+=" --kubeconfig=/etc/srv/kubernetes/kube-controller-manager/kubeconfig"
+  params+=" --leader-elect=false"
   params+=" --root-ca-file=${CA_CERT_BUNDLE_PATH}"
   params+=" --service-account-private-key-file=${SERVICEACCOUNT_KEY_PATH}"
   if [[ -n "${ENABLE_GARBAGE_COLLECTOR:-}" ]]; then
diff --git a/cluster/gce/gci/configure-helper.sh b/cluster/gce/gci/configure-helper.sh
index 34825f6..0535e21 100644
--- a/cluster/gce/gci/configure-helper.sh
+++ b/cluster/gce/gci/configure-helper.sh
@@ -124,7 +124,7 @@ function main() {
     start-kube-controller-manager
     start-kube-scheduler
     wait-till-apiserver-ready
-    start-workload-controller-manager
+    #start-workload-controller-manager
     start-kube-addons
     start-cluster-autoscaler
     start-lb-controller
diff --git a/cmd/kube-controller-manager/app/controllermanager.go b/cmd/kube-controller-manager/app/controllermanager.go
index ae0ab14..02b15c5 100644
--- a/cmd/kube-controller-manager/app/controllermanager.go
+++ b/cmd/kube-controller-manager/app/controllermanager.go
@@ -389,8 +389,8 @@ func NewControllerInitializers(loopMode ControllerLoopMode) map[string]InitFunc
        controllers["garbagecollector"] = startGarbageCollectorController
        controllers["daemonset"] = startDaemonSetController
        controllers["job"] = startJobController
-       //controllers["deployment"] = startDeploymentController
-       //controllers["replicaset"] = startReplicaSetController
+       controllers["deployment"] = startDeploymentController
+       controllers["replicaset"] = startReplicaSetController
        controllers["horizontalpodautoscaling"] = startHPAController
        controllers["disruption"] = startDisruptionController
        controllers["statefulset"] = startStatefulSetController
```
7. make clean & make quick-release
8. run ./cluster/kube-up.sh to start cluster
5. check endpoints
```
$ kubectl get endpoints --all-namespaces
NAMESPACE     NAME                   ENDPOINTS                                                     AGE     SERVICEGROUPID
default       kubernetes             34.94.73.126:443                                              3h47m   0
kube-system   default-http-backend   10.64.3.4:8080                                                3h47m
kube-system   heapster               10.64.4.2:8082                                                3h47m
kube-system   kube-scheduler         <none>                                                        3h47m   <none>
kube-system   kubernetes-dashboard   10.64.2.3:8443                                                3h47m
kube-system   metrics-server         10.64.7.2:443                                                 3h47m
kubemark      kube-dns               10.64.6.3:53,10.64.6.3:53                                     3h39m
```
**Anything else we need to know?**:
https://github.com/futurewei-cloud/arktos/issues/96
**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Sindica** [comment]
Log in kubeproxy-hollow-node seems related:

Looks like it is forcing resync every 30s. This does not look good.

I0708 00:42:41.496911       7 reflector.go:361] k8s.io/client-go/informers/factory.go:145: forcing resync
I0708 00:42:41.575839       7 reflector.go:361] k8s.io/client-go/informers/factory.go:145: forcing resync
I0708 00:43:11.497099       7 reflector.go:361] k8s.io/client-go/informers/factory.go:145: forcing resync
I0708 00:43:11.576027       7 reflector.go:361] k8s.io/client-go/informers/factory.go:145: forcing resync

It caused endpoints being update in kubeproxy every 30s.

I0708 00:43:11.576211       7 endpoints.go:277] Setting endpoints for "/kube-system/kubernetes-dashboard:" to [10.245.130.56:8443]
I0708 00:43:11.576232       7 endpoints.go:277] Setting endpoints for "/kube-system/kubernetes-dashboard:" to [10.245.130.56:8443]
I0708 00:43:41.576410       7 endpoints.go:277] Setting endpoints for "/default/kubernetes:https" to [34.94.208.105:443]
I0708 00:43:41.576439       7 endpoints.go:277] Setting endpoints for "/default/kubernetes:https" to [34.94.208.105:443 34.94.221.148:443]
I0708 00:43:41.576454       7 endpoints.go:277] Setting endpoints for "/default/kubernetes:https" to [34.94.208.105:443]
I0708 00:43:41.576466       7 endpoints.go:277] Setting endpoints for "/default/kubernetes:https" to [34.94.208.105:443 34.94.221.148:443]
I0708 00:43:41.576507       7 endpoints.go:277] Setting endpoints for "/kube-system/kubernetes-dashboard:" to [10.245.130.56:8443]
I0708 00:43:41.576530       7 endpoints.go:277] Setting endpoints for "/kube-system/kubernetes-dashboard:" to [10.245.130.56:8443]
I0708 00:44:11.576669       7 endpoints.go:277] Setting endpoints for "/default/kubernetes:https" to [34.94.208.105:443]
I0708 00:44:11.576686       7 endpoints.go:277] Setting endpoints for "/default/kubernetes:https" to [34.94.208.105:443 34.94.221.148:443]
I0708 00:44:11.576697       7 endpoints.go:277] Setting endpoints for "/default/kubernetes:https" to [34.94.208.105:443]
I0708 00:44:11.576706       7 endpoints.go:277] Setting endpoints for "/default/kubernetes:https" to [34.94.208.105:443 34.94.221.148:443]
I0708 00:44:11.576745       7 endpoints.go:277] Setting endpoints for "/kube-system/kubernetes-dashboard:" to [10.245.130.56:8443]
I0708 00:44:11.576759       7 endpoints.go:277] Setting endpoints for "/kube-system/kubernetes-dashboard:" to [10.245.130.56:8443]
I0708 00:44:14.367887       7 endpoints.go:277] Setting endpoints for "/kube-system/kubernetes-dashboard:" to [10.245.130.56:8443]
I0708 00:44:14.367908       7 endpoints.go:277] Setting endpoints for "/kube-system/kubernetes-dashboard:" to []
I0708 00:44:14.367930       7 endpoints.go:277] Setting endpoints for "/kube-system/kubernetes-dashboard:" to []
I0708 00:44:41.576933       7 endpoints.go:277] Setting endpoints for "/kube-system/kubernetes-dashboard:" to []
I0708 00:44:41.576990       7 endpoints.go:277] Setting endpoints for "/kube-system/kubernetes-dashboard:" to []
I0708 00:44:41.577057       7 endpoints.go:277] Setting endpoints for "/default/kubernetes:https" to [34.94.208.105:443]
I0708 00:44:41.577075       7 endpoints.go:277] Setting endpoints for "/default/kubernetes:https" to [34.94.208.105:443 34.94.221.148:443]
I0708 00:44:41.577090       7 endpoints.go:277] Setting endpoints for "/default/kubernetes:https" to [34.94.208.105:443]
I0708 00:44:41.577103       7 endpoints.go:277] Setting endpoints for "/default/kubernetes:https" to [34.94.208.105:443 34.94.221.148:443]
I0708 00:45:11.577103       7 endpoints.go:277] Setting endpoints for "/kube-system/kubernetes-dashboard:" to []
I0708 00:45:11.577120       7 endpoints.go:277] Setting endpoints for "/kube-system/kubernetes-dashboard:" to []
I0708 00:45:11.577167       7 endpoints.go:277] Setting endpoints for "/default/kubernetes:https" to [34.94.208.105:443]
I0708 00:45:11.577183       7 endpoints.go:277] Setting endpoints for "/default/kubernetes:https" to [34.94.208.105:443 34.94.221.148:443]
I0708 00:45:11.577193       7 endpoints.go:277] Setting endpoints for "/default/kubernetes:https" to [34.94.208.105:443]
I0708 00:45:11.577202       7 endpoints.go:277] Setting endpoints for "/default/kubernetes:https" to [34.94.208.105:443 34.94.221.148:443]

**Comment by Sindica** [comment]
Local arktos kube-proxy.log has setting endpoints every 15 min.

**Comment by sonyafenge** [comment]
close this issue because we are replacing workload-controller with scale-out solution
