### ISSUE TITLE
Flaky Arktos Unit Tests

### ISSUE THREAD

**Issue by chenqianfzh** [CentaurusInfra/arktos#500]
Recently the following unit tests in Arktos are pretty flaky.

* //staging/src/k8s.io/apiserver/pkg/storage/etcd3:go_default_test          
* //staging/src/k8s.io/client-go/tools/cache:go_default_test         
* //cmd/kube-scheduler/app/options:go_default_test                     

The following is an example test run on a PR, which does not make any change to golang code. 
https://jenkins.alkaidcloud.io/job/arktos-pr-tests/1881/console

Those test were passing on a re-run. 
https://jenkins.alkaidcloud.io/job/arktos-pr-tests/1882/

**Comment by Sindica** [comment]
I was able to reproduce UT failure in //cmd/kube-scheduler/app/options:go_default_test for TestSchedulerOptions. Filed a separate issue for it. https://github.com/futurewei-cloud/arktos/issues/507
