### ISSUE TITLE
Tenants stay in Terminating status after perf test resource cleanup

### ISSUE THREAD

**Issue by jshaofuturewei** [CentaurusInfra/arktos#551]
**What happened**:

The current tenant is [{{ } {apivu0-testtenant    /api/v1/tenants/apivu0-testtenant cc7d6bed-30d7-4c92-88c9-1eceaf157fb6 4606308852368039408 837186184882946049 0 2020-08-07 12:24:51 +0000 UTC 2020-08-07 13:12:05 +0000 UTC <nil> map[] map[] [] nil []  []} {[arktos] 0} {Terminating}} {{ } {ewkofo-testtenant    /api/v1/tenants/ewkofo-testtenant 16786a9a-e45c-46a2-9de1-4b95ebbb1b46 2809432893473647024 837186184881897473 0 2020-08-07 12:12:31 +0000 UTC 2020-08-07 13:12:05 +0000 UTC <nil> map[] map[] [] nil []  []} {[arktos] 0} {Terminating}} {{ } {iji6fe-testtenant    /api/v1/tenants/iji6fe-testtenant 708bfced-3bae-4c6d-badf-11b1319db1cc 4998388524346924560 837186184881373185 0 2020-08-07 12:07:41 +0000 UTC 2020-08-07 13:12:05 +0000 UTC <nil> map[] map[] [] nil []  []} {[arktos] 0} {Terminating}} {{ } {okylhk-testtenant    /api/v1/tenants/okylhk-testtenant a64f8fc5-cd95-4980-92a7-63ffc4199467 4648677421855445695 837186184883470337 0 2020-08-07 12:22:06 +0000 UTC 2020-08-07 13:12:05 +0000 UTC <nil> map[] map[] [] nil []  []} {[arktos] 0} {Terminating}} {{ } {rb9d8a-testtenant    /api/v1/tenants/rb9d8a-testtenant 5d3a0b98-d756-4ba5-8ab6-7b55838efa14 943232548159769529 837186184881897474 0 2020-08-07 12:18:30 +0000 UTC 2020-08-07 13:12:05 +0000 UTC <nil> map[] map[] [] nil []  []} {[arktos] 0} {Terminating}} {{ } {system    /api/v1/tenants/system a3724c7e-5d02-4a08-9d43-f0c0ee3d06c4 8118941018801997139 837147682965815297 0 2020-08-06 16:48:09 +0000 UTC <nil> <nil> map[] map[] [] nil []  []} {[arktos] 0} {Active}} {{ } {y4wgmg-testtenant    /api/v1/tenants/y4wgmg-testtenant 04b86f5a-7e99-4053-b319-1c7ae29628a4 9115535333748280980 837186184773369857 0 2020-08-07 12:08:46 +0000 UTC 2020-08-07 13:12:05 +0000 UTC <nil> map[] map[] [] nil []  []} {[arktos] 0} {Terminating}}]I0807 13:50:15.438614    2771 simple_test_executor.go:74] Waiting for the chaos monkey subroutine to end...

**What you expected to happen**:

All the tenants are removed

**How to reproduce it (as minimally and precisely as possible)**:
Fetched my latest branch https://github.com/jshaofuturewei/arktos/tree/create_tenant
 ./run-e2e.sh --nodes=100  --provider=kubemark --kubeconfig=$HOME/go/src/k8s.io/arktos/test/kubemark/resources/kubeconfig.kubemark --report-dir=$REPORTDIR --testconfig=testing/density/config.yaml 

**Anything else we need to know?**:

**Environment**:
- Arktos version (use `kubectl version`):
https://github.com/jshaofuturewei/arktos/tree/create_tenant

- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by jshaofuturewei** [comment]
It can be deleted now. However, it takes minutes to do it.

Please see attached.  A kubectl delete might take around 1 minutes, which is quicker.

![image](https://user-images.githubusercontent.com/50841010/89822812-3a709e80-db05-11ea-82a5-016e14a4d057.png)

**Comment by chenqianfzh** [comment]
Joe: 
I found a bug in https://github.com/jshaofuturewei/arktos/commit/0d6d5b1a842f6a8930f4ff2e71cb88d22e97f5c5 and left a comment. Could you update the code?

Qian

**Comment by jshaofuturewei** [comment]
Thanks and updated. However, it is not related to tenant deletion especially for new created tenants.

> Joe:
> I found a bug in [jshaofuturewei@0d6d5b1](https://github.com/jshaofuturewei/arktos/commit/0d6d5b1a842f6a8930f4ff2e71cb88d22e97f5c5) and left a comment. Could you update the code?
> 
> Qian

**Comment by chenqianfzh** [comment]
Per offline discussion, I will jump in if there is another repro. So far, I could not repro it in my local env.

**Comment by chenqianfzh** [comment]
close it as it is not actively reproing. Feel free to reopen if it is back.
