### ISSUE TITLE
[Bug]: API server config update "concurrent map iteration and map write"

### ISSUE THREAD

**Issue by Sindica** [CentaurusInfra/arktos#639]
**What happened**:
Aug 30 18:13:16 upgrade15000-3api-2wc-1etcd-kubemark-master kubelet[3428]: fatal error: concurrent map iteration and map write
Aug 30 18:13:16 upgrade15000-3api-2wc-1etcd-kubemark-master kubelet[3428]: goroutine 345 [running]:
Aug 30 18:13:16 upgrade15000-3api-2wc-1etcd-kubemark-master kubelet[3428]: runtime.throw(0x40e810c, 0x26)
Aug 30 18:13:16 upgrade15000-3api-2wc-1etcd-kubemark-master kubelet[3428]:         /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc001235c70 sp=0xc001235c40 pc=0x4308f2
Aug 30 18:13:16 upgrade15000-3api-2wc-1etcd-kubemark-master kubelet[3428]: runtime.mapiternext(0xc001235ed8)
Aug 30 18:13:16 upgrade15000-3api-2wc-1etcd-kubemark-master kubelet[3428]:         /usr/local/go/src/runtime/map.go:860 +0x597 fp=0xc001235cf8 sp=0xc001235c70 pc=0x411ee7
Aug 30 18:13:16 upgrade15000-3api-2wc-1etcd-kubemark-master kubelet[3428]: runtime.mapiterinit(0x37a1400, 0xc0013148d0, 0xc001235ed8)
Aug 30 18:13:16 upgrade15000-3api-2wc-1etcd-kubemark-master kubelet[3428]:         /usr/local/go/src/runtime/map.go:850 +0x1c9 fp=0xc001235d18 sp=0xc001235cf8 pc=0x411859
Aug 30 18:13:16 upgrade15000-3api-2wc-1etcd-kubemark-master kubelet[3428]: k8s.io/kubernetes/vendor/k8s.io/client-go/rest.(*Config).updateConfig(0xc000fa7ec0)
Aug 30 18:13:16 upgrade15000-3api-2wc-1etcd-kubemark-master kubelet[3428]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/config.go:195 +0x306 fp=0xc001235f48 sp=0xc001235d18 pc=0xcaa4c6
Aug 30 18:13:16 upgrade15000-3api-2wc-1etcd-kubemark-master kubelet[3428]: k8s.io/kubernetes/vendor/k8s.io/client-go/rest.NewAggregatedConfig.func1(0xc000fa7ec0)
Aug 30 18:13:16 upgrade15000-3api-2wc-1etcd-kubemark-master kubelet[3428]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/config.go:84 +0xc3 fp=0xc001235fd8 sp=0xc001235f48 pc=0xcb8023
Aug 30 18:13:16 upgrade15000-3api-2wc-1etcd-kubemark-master kubelet[3428]: runtime.goexit()
Aug 30 18:13:16 upgrade15000-3api-2wc-1etcd-kubemark-master kubelet[3428]:         /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc001235fe0 sp=0xc001235fd8 pc=0x45fbd1
Aug 30 18:13:16 upgrade15000-3api-2wc-1etcd-kubemark-master kubelet[3428]: created by k8s.io/kubernetes/vendor/k8s.io/client-go/rest.NewAggregatedConfig
Aug 30 18:13:16 upgrade15000-3api-2wc-1etcd-kubemark-master kubelet[3428]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/client-go/rest/config.go:81 +0xdc
Aug 30 18:13:16 upgrade15000-3api-2wc-1etcd-kubemark-master kubelet[3428]: goroutine 1 [select, 1 minutes]:
Aug 30 18:13:16 upgrade15000-3api-2wc-1etcd-kubemark-master kubelet[3428]: k8s.io/kubernetes/cmd/kubelet/app.run(0xc0006da600, 0xc0007d6140, 0xc000222ae0, 0xc, 0xc000ec3af8)
Aug 30 18:13:16 upgrade15000-3api-2wc-1etcd-kubemark-master kubelet[3428]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:769 +0xac7
Aug 30 18:13:16 upgrade15000-3api-2wc-1etcd-kubemark-master kubelet[3428]: k8s.io/kubernetes/cmd/kubelet/app.Run(0xc0006da600, 0xc0007d6140, 0xc000222ae0, 0xc000b00a80, 0xc0005a4460)
Aug 30 18:13:16 upgrade15000-3api-2wc-1etcd-kubemark-master kubelet[3428]:         /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubelet/app/server.go:431 +0x112

**What you expected to happen**:
No concurrent map iteration and map write

**How to reproduce it (as minimally and precisely as possible)**:
Looks like when client got api server configuration update information, it trying to update its kubeconfig. At the same time, API server configuration was updated again.

**Anything else we need to know?**:

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Sindica** [comment]
https://github.com/futurewei-cloud/arktos/pull/640

**Comment by sonyafenge** [comment]
one more repro:
```
10k nodes started successfully, and after create pods from 100k->200K, cluster crashed with this panic in apiserver.log
E0831 03:05:30.789224       1 metrics.go:96] Error in audit plugin 'buffered' affecting 1 audit events: audit buffer queue blocked
Impacted events:
2020-08-31T03:05:30.788529195Z AUDIT: id="1476c2d4-6423-41b8-982e-74276d94e7c6" stage="ResponseStarted" ip="10.64.44.26" method="watch" user="kubecfg" groups="\"system:masters\",\"system:authenticated\"" as="<self>" asgroups="<lookup>" namespace="<none>" uri="/api/v1/services?resourceVersion=838249469155213312&timeoutSeconds=504&watch=true" response="200"
E0831 03:05:30.789382       1 metrics.go:96] Error in audit plugin 'buffered' affecting 1 audit events: audit buffer queue blocked
Impacted events:
2020-08-31T03:05:30.788940453Z AUDIT: id="c6d60e51-0884-4f41-aac8-6f13690e3d1c" stage="ResponseStarted" ip="10.64.144.70" method="watch" user="kubecfg" groups="\"system:masters\",\"system:authenticated\"" as="<self>" asgroups="<lookup>" namespace="<none>" uri="/api/v1/actions?fieldSelector=spec.nodeName%3Dhollow-node-prn2j&resourceVersion=838254265199755264&timeoutSeconds=485&watch=true" response="200"
E0831 03:05:30.789487       1 metrics.go:96] Error in audit plugin 'buffered' affecting 1 audit events: audit buffer queue blocked
Impacted events:
2020-08-31T03:05:30.389760808Z AUDIT: id="0305072a-1c17-4be2-97d1-5ddf310cd698" stage="ResponseStarted" ip="10.64.7.44" method="watch" user="kubecfg" groups="\"system:masters\",\"system:authenticated\"" as="<self>" asgroups="<lookup>" namespace="wos58ylrgr1qvuclr18r0lzykwxayh35-ns" uri="/api/v1/tenants/system/namespaces/wos58ylrgr1qvuclr18r0lzykwxayh35-ns/secrets?allowPartialWatch=true&fieldSelector=metadata.name%3Ddefault-token-mltnf&resourceVersion=838253402356973571&timeout=6m33s&timeoutSeconds=393&watch=true" response="200"
E0831 03:05:30.789547       1 metrics.go:96] Error in audit plugin 'buffered' affecting 1 audit events: audit buffer queue blocked
Impacted events:
2020-08-31T03:05:30.738846279Z AUDIT: id="c0562b3d-9dbf-40b3-9ab6-42301d91c0dc" stage="ResponseComplete" ip="10.64.117.2" method="watch" user="kubecfg" groups="\"system:masters\",\"system:authenticated\"" as="<self>" asgroups="<lookup>" namespace="dnghadb5awcrhva576frbeq1wigjlry0-ns" uri="/api/v1/tenants/system/namespaces/dnghadb5awcrhva576frbeq1wigjlry0-ns/secrets?allowPartialWatch=true&fieldSelector=metadata.name%3Ddefault-token-pssxg&resourceVersion=838253402356973571&timeout=8m37s&timeoutSeconds=517&watch=true" response="200"
fatal error: concurrent map iteration and map write
…

```
Logs are located under workload-controller-manger project at:  sonya-uswest2: /home/sonyali/logs/perf-test/gce-10000/arktos/0830-build0817-upgrade15000-3api-2wc-1etcd/logs/crashed

**Comment by Sindica** [comment]
This issue should be resolve with commit https://github.com/futurewei-cloud/arktos/pull/640 and https://github.com/futurewei-cloud/arktos/pull/678

**Comment by sonyafenge** [comment]
### 9/4/2020 [scalability][arktos][node10K][Fixverify] node10k-3a3c1e
Started a 10K nodes run with 3 apiserver, 3 workload, 1 etcd to verify this fix. Cluster crashed when create 100K -> 200K pods with issue: #687.
Didn't find repro for this issue.

**Comment by sonyafenge** [comment]
### 9/9/2020 [perf-tests][arktos][node5000][workloadDisabled] openfiles-3a0w1e
5k nodes run with 3 apiserver/0 workload/1 etcd(3.4.4) failed with this issue: #701.
Didn't find repro for this issue.

**Comment by sonyafenge** [comment]
### 9/10/2020 [perf-tests][arktos][node5000][workloadDisabled] openfiles-3a0w1e
5k nodes run with 3 apiserver/0 workload/1 etcd(3.4.4) and update master ulimit -n 200000, didn't get a repro for this isue.

```
commit 994de1da91763eeaec84a4cc0e979be7c9d16ffa
Author: sonyafenge <sonyafenge@gmail.com>
Date:   Wed Sep 9 02:51:40 2020 +0000

    ETCD3.4.4

commit 6028259e93e00e3b09906560d94e377efa5fd4f3
Author: sonyafenge <sonyafenge@gmail.com>
Date:   Fri Aug 28 21:32:26 2020 +0000

    disable workload-controller-manager

commit 4cee1c408be137d3d281ce8ed25eb80a2ef70775
Author: Ying Huang <sindica2000@yahoo.com>
Date:   Wed Sep 9 18:28:43 2020 +0000

    API server config read lock. (#692)
```
logs can be found under GCP project: workload-controller-manager:
```
sonya-uswest2:  /home/sonyali/logs/perf-test/gce-5000/arktos/0910-openfiles-3a0w1e 
```

**Comment by sonyafenge** [comment]
### 9/10/2020 [perf-tests][arktos][node5000][workloadDisabled] etcd344-3a0w1e
5k nodes run with 3 apiserver/0 workload/1 etcd(3.4.4) and use the default ulimit -n 1024 for master, didn't get a repro for this isue.
```
commit 994de1da91763eeaec84a4cc0e979be7c9d16ffa
Author: sonyafenge <sonyafenge@gmail.com>
Date:   Wed Sep 9 02:51:40 2020 +0000

    ETCD3.4.4

commit 6028259e93e00e3b09906560d94e377efa5fd4f3
Author: sonyafenge <sonyafenge@gmail.com>
Date:   Fri Aug 28 21:32:26 2020 +0000

    disable workload-controller-manager

commit 4cee1c408be137d3d281ce8ed25eb80a2ef70775
Author: Ying Huang <sindica2000@yahoo.com>
Date:   Wed Sep 9 18:28:43 2020 +0000

    API server config read lock. (#692)
```
logs can be found under GCP project: workload-controller-manager:
```
sonya-useast1:  /home/sonyali/logs/perf-test/gce-5000/arktos/0910-etcd344-3a0w1e 
```

**Comment by sonyafenge** [comment]
### 9/11/2020 [perf-tests][arktos]
Two runs on Friday, both disabled workload-controller-manager and has ETCD 3.4.4 with 3 apiserver, 0 workload, 1 wtcd:
1. 10K runs started from density testing,  density testing failed with 3 other issues, but no repro for this issue.
2. 5K runs started from load testing, load testing failed with 4 other issues, but no repro for this issue.
