### ISSUE TITLE
bug: concurrent map iteration and map write in AggregatedWatcher GetErrors

### ISSUE THREAD

**Issue by Sindica** [CentaurusInfra/arktos#650]
**What happened**:
fatal error: concurrent map iteration and map write
goroutine 3688815 [running]:
runtime.throw(0x4231200, 0x26)
        /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc4630f5a30 sp=0xc4630f5a00 pc=0x42da52
runtime.mapiternext(0xc4630f5b48)
        /usr/local/go/src/runtime/map.go:860 +0x597 fp=0xc4630f5ab8 sp=0xc4630f5a30 pc=0x40f047
runtime.mapiterinit(0x39409a0, 0xc4b2250f30, 0xc4630f5b48)
        /usr/local/go/src/runtime/map.go:850 +0x1c9 fp=0xc4630f5ad8 sp=0xc4630f5ab8 pc=0x40e9b9
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch.(*AggregatedWatcher).GetErrors(0xc49be20080, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/watch/watch.go:205 +0x79 fp=0xc4630f5bb8 sp=0xc4630f5ad8 pc=0x884539
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry.(*Store).convertToDecoratedWatcher(0xc004f6d900, 0x773b900, 0xc49be20080, 0xc006af4670, 0xf, 0xc21d1ca6b9, 0x12)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:1220 +0x35 fp=0xc4630f5c00 sp=0xc4630f5bb8 pc=0x1501475
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry.(*Store).WatchPredicate(0xc004f6d900, 0x770bc00, 0xc0e557acc0, 0x7744ee0, 0xa3d5da0, 0x7757d20, 0xc49a1c1680, 0x433c6e0, 0x0, 0x0, ...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:1215 +0x15c fp=0xc4630f5d78 sp=0xc4630f5c00 pc=0x150128c
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry.(*Store).Watch(0xc004f6d900, 0x770bc00, 0xc0e557acc0, 0xc498fa5e00, 0x0, 0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/registry/generic/registry/store.go:1200 +0x1ae fp=0xc4630f5ea0 sp=0xc4630f5d78 pc=0x15010ae
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers.ListResource.func1(0x76ffe00, 0xc51781d8f8, 0xc4972caa00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/handlers/get.go:268 +0x76a fp=0xc4630f6540 sp=0xc4630f5ea0 pc=0x1729c4a
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints.restfulListResource.func1(0xc4b2250c30, 0xc0e557aba0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/installer.go:1255 +0x8f fp=0xc4630f6590 sp=0xc4630f6540 pc=0x175424f
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics.InstrumentRouteFunc.func1(0xc4b2250c30, 0xc0e557aba0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/metrics/metrics.go:272 +0x254 fp=0xc4630f6700 sp=0xc4630f6590 pc=0x1027124
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).dispatch(0xc0011fb5f0, 0x76ffd00, 0xc51781d8e8, 0xc4972caa00)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:277 +0x985 fp=0xc4630f6858 sp=0xc4630f6700 pc=0x1014085
k8s.io/kubernetes/vendor/github.com/emicklei/go-restful.(*Container).Dispatch(...)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/emicklei/go-restful/container.go:199

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Sindica** [comment]
PR: https://github.com/futurewei-cloud/arktos/pull/653

**Comment by sonyafenge** [comment]
### 9/4/2020 [scalability][arktos][node10K][Fixverify] node10k-3a3c1e
Started a 10K nodes run with 3 apiserver, 3 workload, 1 etcd to verify this fix. Cluster crashed when create 100K -> 200K pods with issue: #687.

**Comment by sonyafenge** [comment]
### 9/9/2020 [perf-tests][arktos][node5000][workloadDisabled] openfiles-3a0w1e
5k nodes run with 3 apiserver/0 workload/1 etcd(3.4.4) failed with this issue: #701.
Didn't find repro for this issue.

**Comment by sonyafenge** [comment]
### 9/10/2020 [perf-tests][arktos][node5000][workloadDisabled] etcd344-3a0w1e
5k nodes run with 3 apiserver/0 workload/1 etcd(3.4.4) and use the default ulimit -n 1024 for master, didn't get a repro for this isue.
```
commit 994de1da91763eeaec84a4cc0e979be7c9d16ffa
Author: sonyafenge <sonyafenge@gmail.com>
Date:   Wed Sep 9 02:51:40 2020 +0000

    ETCD3.4.4

commit 6028259e93e00e3b09906560d94e377efa5fd4f3
Author: sonyafenge <sonyafenge@gmail.com>
Date:   Fri Aug 28 21:32:26 2020 +0000

    disable workload-controller-manager

commit 4cee1c408be137d3d281ce8ed25eb80a2ef70775
Author: Ying Huang <sindica2000@yahoo.com>
Date:   Wed Sep 9 18:28:43 2020 +0000

    API server config read lock. (#692)
```
logs can be found under GCP project: workload-controller-manager:
```
sonya-useast1:  /home/sonyali/logs/perf-test/gce-5000/arktos/0910-etcd344-3a0w1e 
```

**Comment by sonyafenge** [comment]
### 9/10/2020 [perf-tests][arktos][node5000][workloadDisabled] openfiles-3a0w1e
5k nodes run with 3 apiserver/0 workload/1 etcd(3.4.4) and update master ulimit -n 200000, didn't get a repro for this isue.

```
commit 994de1da91763eeaec84a4cc0e979be7c9d16ffa
Author: sonyafenge <sonyafenge@gmail.com>
Date:   Wed Sep 9 02:51:40 2020 +0000

    ETCD3.4.4

commit 6028259e93e00e3b09906560d94e377efa5fd4f3
Author: sonyafenge <sonyafenge@gmail.com>
Date:   Fri Aug 28 21:32:26 2020 +0000

    disable workload-controller-manager

commit 4cee1c408be137d3d281ce8ed25eb80a2ef70775
Author: Ying Huang <sindica2000@yahoo.com>
Date:   Wed Sep 9 18:28:43 2020 +0000

    API server config read lock. (#692)
```
logs can be found under GCP project: workload-controller-manager:
```
sonya-uswest2:  /home/sonyali/logs/perf-test/gce-5000/arktos/0910-openfiles-3a0w1e 
```

**Comment by sonyafenge** [comment]
### 9/11/2020 [perf-tests][arktos]
Two runs on Friday, both disabled workload-controller-manager and has ETCD 3.4.4 with 3 apiserver, 0 workload, 1 wtcd:
1. 10K runs started from density testing,  density testing failed with 3 other issues, but no repro for this issue.
2. 5K runs started from load testing, load testing failed with 4 other issues, but no repro for this issue.
