### ISSUE TITLE
 [Perf-tests: arktos][node5000+]too high latency 99th percentile

### ISSUE THREAD

**Issue by sonyafenge** [CentaurusInfra/arktos#652]
**What happened**:

node5000 perf-tests run recently has too high latency 99th percentile error:
```    
Errors: [measurement call WaitForControlledPodsRunning - WaitForRunningSaturationDeployments error: 3 objects timed out: Deployments: rrxp9q-testns/saturation-deployment-0, oj6uj5-testns/saturation-deployment-0, wbn2xs-testns/saturation-deployment-0
measurement call PodStartupLatency - PodStartupLatency error: pod startup: too high latency 99th percentile: got 5.453821139s expected: 5s]
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by sonyafenge** [comment]
based on information in this article: https://github.com/kubernetes/kubernetes/issues/66672, updated log-level from v4 to v2,    still see this error.

**Comment by sonyafenge** [comment]
Item | unit |   |   |   |   |   |  
-- | -- | -- | -- | -- | -- | -- | --
  |   | Perc50 | Perc90 | Perc99 | Perc50 | Perc90 | Perc99
create_to_schedule | ms | 0 | 0 | 4000 | 0 | 0 | 3000
pod_startup | ms | 1882.51527 | 3119.05058 | 6596.07522 | 1876.31453 | 2680.87832 | 5453.82114
run_to_watch | ms | 1094.38652 | 1861.56714 | 3649.82398 | 1097.61235 | 1826.74806 | 2294.00316
schedule_to_run | ms | 1000 | 1000 | 3000 | 1000 | 1000 | 1000
schedule_to_watch | ms | 1837.76518 | 2672.05042 | 5371.41867 | 1803.75292 | 2560.2636 | 4034.17799

**Comment by yb01** [comment]
Analyzing the current results:

1. the timestamp entries:
per the code in perf test below,  current 4 timestamps were captured:
T1: pod created at API Server
T2: pod scheduled
T3: pod created, all containers started, at least 1 container running
T4: pod running phase updated to API server

Item | unit 
create_to_schedule | ms 
pod_startup | ms
run_to_watch | ms 
schedule_to_run | ms 
schedule_to_watch | ms 


```
func (p *podStartupLatencyMeasurement) checkPod(_, obj interface{}) {
   if obj == nil {
      return
   }
   pod, ok := obj.(*corev1.Pod)
   if !ok {
      return
   }
   if pod.Status.Phase == corev1.PodRunning {
      key := createMetaNamespaceKey(pod.Namespace, pod.Name)
      if _, found := p.podStartupEntries.Get(key, createPhase); !found {
         p.podStartupEntries.Set(key, watchPhase, time.Now())
         p.podStartupEntries.Set(key, createPhase, pod.CreationTimestamp.Time)
         var startTime metav1.Time
         for _, cs := range pod.Status.ContainerStatuses {
            if cs.State.Running != nil {
               if startTime.Before(&cs.State.Running.StartedAt) {
                  startTime = cs.State.Running.StartedAt
               }
            }
         }
         if startTime != metav1.NewTime(time.Time{}) {
            p.podStartupEntries.Set(key, runPhase, startTime.Time)
         } else {
            klog.Errorf("%s: pod %v (%v) is reported to be running, but none of its containers is", p, pod.Name, pod.Namespace)
         }
      }
   }
}

podStartupLatency := p.podStartupEntries.CalculateTransitionsLatency(map[string]measurementutil.Transition{
 "create_to_schedule": {
 From: createPhase,
 To: schedulePhase,
 },
 "schedule_to_run": {
 From: schedulePhase,
 To: runPhase,
 },
 "run_to_watch": {
 From: runPhase,
 To: watchPhase,
 },
 "schedule_to_watch": {
 From: schedulePhase,
 To: watchPhase,
 },
 "pod_startup": {
 From: createPhase,
 To: watchPhase,
 Threshold: p.threshold,
 },
 })
```

**Comment by yb01** [comment]
Will need capture and review more breakdown data to analyze further.

**Comment by sonyafenge** [comment]
close this issue because we are replacing multiapiserver with scale-out solution
