### ISSUE TITLE
Panic: ”too many open files in system“ in apiserver/pkg/server/secure_serving.go

### ISSUE THREAD

**Issue by sonyafenge** [CentaurusInfra/arktos#701]
**What happened**:
run perf-tests with 3 apiserver and got panic:
```
E0910 07:23:54.681105       1 runtime.go:71] Observed a panic: Stopped listening on [::]:10251 due to error: accept tcp [::]:10251: accept4: too many open files in system
goroutine 807 [running]:
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x16ebc80, 0xc03e546f60)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:69 +0x7b
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51 +0x82
panic(0x16ebc80, 0xc03e546f60)
        /usr/local/go/src/runtime/panic.go:522 +0x1b5
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.RunServer.func2(0x1ca0740, 0xc00000e058, 0xc0002c9c70, 0xc0002cc5a0)
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/secure_serving.go:162 +0x39a
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.RunServer
        /go/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/secure_serving.go:146 +0x176
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
both $ ulimit -n have this repro
```
65535
or 
1024
```
**Anything else we need to know?**:
logs can be found under GCP project: workload-controller-manager: 
sonya-uswest2: /home/sonyali/logs/perf-test/gce-5000/arktos/0909-openfiles-3a0w1e
**Environment**:
- Arktos version (use `kubectl version`):
```
commit 994de1da91763eeaec84a4cc0e979be7c9d16ffa
Author: sonyafenge <sonyafenge@gmail.com>
Date:   Wed Sep 9 02:51:40 2020 +0000

    ETCD3.4.4

commit 6028259e93e00e3b09906560d94e377efa5fd4f3
Author: sonyafenge <sonyafenge@gmail.com>
Date:   Fri Aug 28 21:32:26 2020 +0000

    disable workload-controller-manager

commit 4cee1c408be137d3d281ce8ed25eb80a2ef70775
Author: Ying Huang <sindica2000@yahoo.com>
Date:   Wed Sep 9 18:28:43 2020 +0000

    API server config read lock. (#692)

commit a4f890fc3308b6c6d77823d758f47faebc912b11
Author: chenqianfzh <51831990+chenqianfzh@users.noreply.github.com>
Date:   Tue Sep 8 22:43:57 2020 -0700

    update e2e test cases for multi-tenancy controllers (#677)
```
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by sonyafenge** [comment]
### 9/10/2020 [perf-tests][arktos][node5000][workloadDisabled] openfiles-3a0w1e
5k nodes run with 3 apiserver/0 workload/1 etcd(3.4.4) and update master ulimit -n 200000, didn't get a repro for this isue.

```
commit 994de1da91763eeaec84a4cc0e979be7c9d16ffa
Author: sonyafenge <sonyafenge@gmail.com>
Date:   Wed Sep 9 02:51:40 2020 +0000

    ETCD3.4.4

commit 6028259e93e00e3b09906560d94e377efa5fd4f3
Author: sonyafenge <sonyafenge@gmail.com>
Date:   Fri Aug 28 21:32:26 2020 +0000

    disable workload-controller-manager

commit 4cee1c408be137d3d281ce8ed25eb80a2ef70775
Author: Ying Huang <sindica2000@yahoo.com>
Date:   Wed Sep 9 18:28:43 2020 +0000

    API server config read lock. (#692)
```

**Comment by jshaofuturewei** [comment]
9/10/2020 [perf-tests][arktos][node5000]
5k nodes run with 2 apiserver/1 workload/1 etcd(3.4.4-arktos.1) and use the default ulimit -n 1024 for master, build on the commit on master a1afd44baab7ae72b56485dd0cf22c7957019410 does not reproduce the issue.

**Comment by jshaofuturewei** [comment]
Check all the created nodes and found all of them use default open file settings, which is 1024.

shaoj9@node5000-3api-2wc-1etcd-kubemark-master ~ $ ulimit -a
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 2515551
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 2515551
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

Considering to add custormized LimitNOFILE to node.yaml.

**Comment by zmn223** [comment]
Did not repro in last Friday's (9/11) run

**Comment by jshaofuturewei** [comment]
Neither 65535 nor 1024 take effect unless it is a docker config setting

node5000-3api-2wc-1etcd-master /var/log # systemctl show docker | grep NOFILE
LimitNOFILE=1048576
LimitNOFILESoft=1048576

The default value is 1048576 which is big enough for open files.

If we degrade the nofile to 1024, the issue might be reproduced. However, it depends on the environment of running kubemark.

**Comment by sonyafenge** [comment]
close this issue because we are replacing multiapiserver with scale-out solution
