### ISSUE TITLE
update golang to 1.13.9

### ISSUE THREAD

**Issue by sonyafenge** [CentaurusInfra/arktos#891]
**What happened**:
arktos is still support golang 1.12.9, update golang to 1.13.9
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Arktos version (use `kubectl version`):
- Cloud provider or hardware configuration:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Install tools:
- Network plugin and version (if this is a network-related bug):
- Others:

**Comment by Fizzbb** [comment]
hi there, does Arktos support go 1.13.9 now? when I clone the repo and make, error shows K8s requires 1.13.9.

**Comment by sonyafenge** [comment]
yes, it is merged to master yesterday.

**Comment by sonyafenge** [comment]
PR has been merges. closing this issue.
